### PR TITLE
fix(cache): isolate cache keys per provider name and options

### LINKED ISSUE #184: Cache does not take provider config into account
### 🐛 The bug

Currently, `resolveFont` for each provider is cached using a key that is partially made of the family options hash. That's great but if you use some providers options then change them, cache is not invalidated.

### 🛠️ To reproduce

https://stackblitz.com/edit/github-pkgkk2lt?file=cache.js

### 🌈 Expected behaviour

Take the provider options into account, when applicable (ie. only for google providers atm).

### ℹ️ Additional context

I'd be happy to submit a PR. Note there's overlap with #183 since the proposed design would solve this issue entirely

### PR DESCRIPTION
**Pull request by sushichan044**
fixes #184 

This PR updates the cache storage generation to automatically include the provider name and options in the cache key. 
Users don’t need to do anything special when defining a provider.

## Additional Context

Purpose 1 of https://github.com/unjs/unifont/pull/239#discussion_r2505972095.

### CODE REVIEW

File: src/cache.ts [hunk 1]
```diff
@@ -22,23 +23,66 @@ export function memoryStorage() {
...
-      await storage.setItem(key, { expires: Date.now() + ONE_WEEK, version, data })
+      await storage.setItem(resolveKey(key), { expires: Date.now() + ONE_WEEK, version, data })
     },
   }
 }
+
+function createCacheKey(...fragments: any[]): string {
+  const parts = fragments.map((f) => {
+    // No hash for string parts for better readability.
+    const part = typeof f === 'string' ? f : hash(f)
```
Comment (sushichan044) [inline src/cache.ts]: For example, if we also hash values like the font provider’s name, it becomes difficult to identify files when checking what Storage has saved. So I think we shouldn’t hash string fields.

**Review by danielroe — APPROVED** [review]
apologies for going back and forth on this.

we should definitely cache by key (font provider) + version of unifont.

my one reservation is that caching uniquely by options too, may be _over_-unique. for example, google fonts will have the same list of fonts, regardless of what options are passed to it. so I'd like to refactor later on to allow providers a _little_ more control over what is dependent on the options and what isn't...

however, I think this is looking really good, and I don't want to hold it up, so I think we can merge and iterate (if you're happy to address the merge conflict 🙏 

thank you for your work on this

**Comment by sushichan044** [comment]
Thanks! I’d forgotten to include the unifont version in the cache key.
 I’ll watch the other PRs and keep iterating on improvements after this one is merged.

**Comment by sushichan044** [comment]
Conflict resolved in https://github.com/unjs/unifont/compare/9f764a10cd601db0add398a6f730db8cbb7cd5f0..1113b6febd3f96d2b4b5d3c69ad180e8f22f642d

This diff is safe because it doesn’t affect any cache-related test cases and CI passes without differences.
